### ISSUE TITLE
Automation - Github actions

### ISSUE THREAD

**Issue by Baklap4** [performous/composer#42]
Within the main repo we've added a bunch of automation for performous
It'd be nice to also apply the findings there to here and create faster releases and build checks.

### Todo

- [ ] Add github workflow (copy paste from [performous/performous](https://github.com/performous/performous/blob/master/.github/workflows/build_and_release.yml))
- [ ] Add Nightly link to readme
- [ ] Add PR commenter (copy paste from [performous/performous](https://github.com/performous/performous/blob/master/.github/workflows/comment_on_pr.yml))
- [ ] Create buildscript for Windows
- [ ] Create buildscript for Linux
- [ ] Create buildscript for OSx
- [ ] Add Github Issue forms

**Comment by Baklap4** [comment]
Couple of items are already done in latest master see PR #46

**Comment by Baklap4** [comment]
@twiecki please watch this issue for new windows binaries :)
